language: cpp

os:
  - osx
  
matrix:
  include:
    - os: osx
      osx_image: xcode8.2

script:
  - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . --target coveralls
